version: '3.1'

services:
    db:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: "postgres"

    user-service:
        build: .
        ports:
            - "8080:8080"
        environment: 
            PG_PASSWORD: "postgres"
        depends_on: 
            - "db"
