version: '3.1'

services:
    db:
        image: postgres
        env_file: 
            - docker.env
        ports:
            - "5432:5432"

    user-service:
        build: .
        ports:
            - "8080:8080"
            - "9000:9000"
        env_file: 
            - docker.env
        depends_on: 
            - "db"
